image: docker:stable
services:
# we will build our images by running docker daemon inside a container
- docker:dind
variables:
  DOCKER_DRIVER: overlay2
  SERVER_DOCKER_IMAGE: popovmi/tictactoe-server

stages:
- build
- trigger

build_server:
  stage: build
  script:
  - docker build -f ./Dockerfile -t $SERVER_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
  - docker tag $SERVER_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $SERVER_DOCKER_IMAGE:latest

define_environment:
  stage: build
  script:
    - node ./kuber/generate-gitlab-ci.js
  artifacts:
    expire_in: 1 week
    paths:
      - dynamic-gitlab-ci.yml

trigger:deploy:
  stage: trigger
  needs:
    - build
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml
        job: build_server
    strategy: depend