image: docker:stable
services:
# we will build our images by running docker daemon inside a container
- docker:dind
variables:
  DOCKER_DRIVER: overlay2
  SERVER_DOCKER_IMAGE: popovmi/tictactoe-server
  GIT_CLONE_PATH: '$CI_BUILDS_DIR/$CI_PROJECT_NAME/$CI_PIPELINE_ID'

stages:
- build
- trigger
- deploy

build_server:
  stage: build
  script:
    - docker build -f ./Dockerfile -t $SERVER_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker tag $SERVER_DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA $SERVER_DOCKER_IMAGE:latest

define_environment:
  stage: build
  script:
    - ./kuber/generate-gitlab-ci.sh
  artifacts:
    expire_in: 1 week
    paths:
      - dynamic-gitlab-ci.yml

trigger:deploy:
  stage: trigger
  needs:
    - build_server
    - define_environment
  trigger:
    include:
      - artifact: dynamic-gitlab-ci.yml
        job: define_environment
    strategy: depend