kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: popovmi-tictactoe-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: {{NAMESPACE}}
  labels:
    project: popovmi-tictactoe
spec:
  ingressClassName: nginx
  rules:
    - host: {{HOSTNAME}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: popovmi-tictactoe-server
                port:
                  number: 80
