kind: Deployment
apiVersion: apps/v1
metadata:
  name: popovmi-tictactoe-server
  namespace: {{NAMESPACE}}
  labels:
    k8s-app: popovmi-tictactoe-server
    project: popovmi-tictactoe
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: popovmi-tictactoe-server
  template:
    metadata:
      name: popovmi-tictactoe-server
      labels:
        k8s-app: popovmi-tictactoe-server
    spec:
      containers:
        - name: popovmi-tictactoe-server
          # this is how we named our docker image
          image: {{SERVER_IMAGE}}
          imagePullPolicy: IfNotPresent
          env:
            - name: CORS_ORIGIN
            - value: {{CORS_ORIGI}}
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: {{NAMESPACE}}-pv
              mountPath: /app/data
      volumes:
        - name: {{NAMESPACE}}-pv
          persistentVolumeClaim:
            claimName: {{NAMESPACE}}-pv-claim
---
kind: Service
apiVersion: v1
metadata:
  name: popovmi-tictactoe-server
  namespace: {{NAMESPACE}}
  labels:
    k8s-app: popovmi-tictactoe-server
    project: popovmi-tictactoe
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    k8s-app: popovmi-tictactoe-server
